config/routes.rb
Rails.application.routes.draw do

  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  resources :feedbacks, only: %i[new create]
  resources :badges, only: :index

  namespace :admin do
    resources :badges

      resources :tests do
       patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

    get 'gists/index'
  end
end

app/models/admin.rb
class Admin < User

  validates :first_name, presence: true
  validates :last_name, presence: true

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  scope :correct, -> { where(correct: true) }

  validates :body, presence: true
  validate :validate_answers_count, on: :create

  private

  def validate_answers_count
    #errors.add(:answer, "Не более 4 ответов") if question.answers.count >= 4
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  RULES = %w[category level first_attempt].freeze

  has_many :users, through: :user_badges
  has_many :user_badges, dependent: :destroy

  validates :title, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tests, dependent: :destroy

  default_scope { order(title: :asc) }

  validates :title, presence: true
end

app/models/create_badge.rb
class CreateBadge < ApplicationRecord
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :user, optional: true

  validates :title, presence: true
  validates :body, presence: true
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category
  has_many :questions, dependent: :destroy
  belongs_to :author, class_name: 'User', optional: true
  has_many :test_passages, dependent: :destroy
  has_many :users, through: :test_passages, dependent: :destroy

  validates :title, presence: true
  validates_numericality_of :level, only_integer: true, grater_than_or_equal_to: 0
  validates :title, uniqueness: { scope: :level }

  scope :easy, -> { where(level: 0..1) }
  scope :medium, -> { where(level: 2..4) }
  scope :hard, -> { where(level: 5..Float::INFINITY) }
  scope :tests_by_category, -> (category) { joins(:category).where(categories: { title: category }) }


  def self.title_by_category(category)
    tests_by_category(category).order(title: :desc).pluck(:title)
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  SUCCESS = 85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, on: :create
  before_validation :before_validation_set_next_question, on: :update

  def accept!(answer_ids)
    if correct_answer?(answer_ids)
      self.correct_questions += 1
    end

    save!
  end

  def completed?
    current_question.nil?
  end

  def success?
    calculation >= SUCCESS
  end

  def test_questions_count
    test.questions.count
  end

  def calculation
    self.correct_questions * 100 / test_questions_count
  end

  def question_index
    test.questions.index(current_question) + 1
  end

  def total_questions
    test.questions.size
  end

  def time_out?
    (Time.now - self.created_at) > test.time_period if test.time_period
  end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def before_validation_set_next_question
    self.current_question = next_question
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort if answer_ids != nil
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question.nil? ? 0 : current_question.id).first
  end
end

app/models/tests_user.rb
class TestsUser < ApplicationRecord
  belongs_to :user
  belongs_to :test
end

app/models/user.rb
class User < ApplicationRecord
  EMAIL_FORMAT = /\A[a-zA-Z0-9._+]+@[a-zA-Zа-яА-Я._+]+\.[a-zа-я]+\z/

  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable,
         :trackable,
         :confirmable

  has_many :test_passages, dependent: :destroy
  has_many :tests, through: :test_passages
  has_many :author_tests, class_name: 'Test', foreign_key: 'author_id', dependent: :destroy
  has_many :gists, dependent: :destroy
  has_many :feedbacks, dependent: :destroy
  has_many :user_badges, dependent: :destroy
  has_many :badges, through: :user_badges

  validates :email, presence: true, uniqueness: true, format: { with: EMAIL_FORMAT }
  #validates :login, presence: true

  def tests_by_level(level)
    tests.where(level: level)
  end

  def completed_tests
    tests.where('test_passages.passed = ?', true)
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end

  def admin?
   is_a?(Admin)
  end
end

app/models/user_badge.rb
class UserBadge < ApplicationRecord
  belongs_to :user
  belongs_to :badge
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController

  before_action :authenticate_user!
  before_action :find_badge, only: %i[show edit update destroy]

  def index
    @badges = Badge.all
  end

  def show
  end

  def new
    @badge = Badge.new
  end

  def edit
  end

  def create
    @badge = Badge.new(badge_params)

    if @badge.save
      redirect_to admin_badges_path(@badge), notice: "Badge has been created"
    else
      render :new
    end
  end

  def destroy
    @badge.destroy

    redirect_to admin_badges_path, notice: "Badge deleted"
  end

  def update
    if @badge.update(badge_params)

      redirect_to admin_badges_path(@badge), notice: "Updated"
    else
      render :edit
    end
  end

  private

  def find_badge
    @badge = Badge.find(params[:id])
  end

  def badge_params
    params.require(:badge).permit(:title, :image_url, :rule_type, :rule_value)
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  before_action :authenticate_user!

  def index
    @badges = Badge.all
    @user_badges = current_user.badges
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_message(name)
    if flash[name] #.any?
      content_tag :p, flash[name], class: "flash #{name}"
    end
  end

  def current_year
    Time.current.year
  end

  def github_link(author, repo)
    link_to 'Test-Guru', "https://github.com/#{author}/#{repo}", target: "_blank"
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
  def badge_image(badge)
    if badge.image_url.present?
      badge_image.url
    else
      asset_path 'award.png'
    end
  end
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper

  def question_header(question)
    if question.new_record?
      "Create New Question: #{@test.title} "
    else
      "Edit Question #{question.test.title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tests_helper.rb
module TestsHelper

TEST_LEVELS = { 0 => :easy, 1 => :elementary, 2 => :advanced, 3 => :hard }.freeze

  def test_level(test)
    TEST_LEVELS[test.level] || :hero
  end
end

app/views/admin/badges/_badge.html.erb
<tr>
	<% if badge.image_url.present? %>
		<td class="align-middle col-md-3"><%= image_tag badge.image_url, size: '70x70' %></td>
	<% else %>
		<td class="align-middle col-md-3"><%= image_tag asset_path 'ruby.png' %></td>
	<% end %>

	<td class="align-middle"><%= badge.title %></td>
	<td class="align-middle"><%= badge.rule_type %></td>
	<td class="align-middle"><%= link_to t('.edit'), edit_admin_badge_path(badge) %>
	</td>
	<td class="align-middle"><%= link_to t('.delete'),
																			 admin_badge_path(badge),
																			 method: :delete,
																			 data: { confirm: t('.choice') } %></td>
</tr>

app/views/admin/badges/_form.html.erb
<%= form_with model: [:admin, @badge], local: true do |form| %>

	<%= render 'shared/errors', resource: @badge %>

	<p>
		<%= form.label :title %><br>
		<%= form.text_field :title %>
	</p>

	<p>
		<%= form.label :image_url %><br>
		<%= form.text_field :image_url %>
	</p>

	<p>
		<%= form.label :rule_type %><br>
		<%= form.select :rule_type, options_for_select(Badge::RULES) %>
	</p>

	<p>
		<%= form.submit t('.create_rule'), class: 'btn btn-primary' %><br>		
	</p>
<% end %>

app/views/admin/badges/edit.html.erb
<h1><%= t('.title')%></h1>
<%= render 'shared/errors', resource: @badge %>

<%= render 'form' %>
<%= link_to t('.back'), admin_badges_path %>

app/views/admin/badges/index.html.erb
<h1><%= t('.admin_header')%></h1>

<p><%= link_to t('.new_badge'), new_admin_badge_path, class: 'btn btn-primary', style: 'color: white' %></p>

<%= render 'shared/errors', resource: @test %>

<table class="table">
	<thead>
		<tr>
			<th><%= t('.image') %></th>
			<th><%= t('.title') %></th>
			<th><%= t('.rule')%></th>
			<th colspan="2"><%= t('.actions')%></th>
		</tr>
	</thead>

	<%= render @badges %>
</table>

app/views/admin/badges/new.html.erb
<h1><%= t('.title')%></h1>

<%= render 'form' %>
<%= link_to t('.back'), admin_badges_path, class: 'btn btn-primary' %>

app/views/badges/_badge.html.erb
<tr>
	<% if badge.image_url.present? %>
		<td class="align-middle col-md-3"><%= image_tag badge.image_url, size: '70x70', alt: "BadgeLogo" %></td>
	<% else %>
		<td class="align-middle col-md-3"><%= image_tag asset_path 'ruby.png' %></td>
	<% end %>
	<td class="align-middle"><%= badge.title %></td>
</tr>

app/views/badges/index.html.erb
<h1><%= t('.header')%></h1>

<%= render 'shared/errors', resource: @test %>

<% if current_user.badges.present? %>
	<h3><%= t('.user_badges')%></h3>
	<table class="table">
		<thead>
			<tr>
				<th><%= t('.image') %></th>
				<th><%= t('.title') %></th>
			</tr>
		</thead>
		<%= render current_user.badges %>
	</table>
<% else %>
	<p class="alert alert-secondary">You are still havn't any badges!</p>
<% end %>

<h3><%= t('.all_badges') %></h3>
<table class="table">
	<thead>
		<tr>
			<th><%= t('.image') %></th>
			<th><%= t('.title') %></th>
		</tr>
	</thead>
	<%= render @badges %>
</table>