config/routes.rb
Rails.application.routes.draw do

  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login, sign_out: :logout }

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  resources :feedbacks, only: %i[new create]
  resources :badges, only: :index

  namespace :admin do
    resources :badges

      resources :tests do
       patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

    get 'gists/index'
  end
end

app/models/admin.rb
class Admin < User

  validates :first_name, presence: true
  validates :last_name, presence: true

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  scope :correct, -> { where(correct: true) }

  validates :body, presence: true
  validate :validate_answers_count, on: :create

  private

  def validate_answers_count
    #errors.add(:answer, "Не более 4 ответов") if question.answers.count >= 4
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
  RULES = %w[category level first_attempt].freeze

  has_many :users, through: :user_badges
  has_many :user_badges, dependent: :destroy

  validates :title, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tests, dependent: :destroy

  default_scope { order(title: :asc) }

  validates :title, presence: true
end

app/models/create_badge.rb
class CreateBadge < ApplicationRecord
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :user, optional: true

  validates :title, presence: true
  validates :body, presence: true
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy
  has_many :gists, dependent: :destroy

  validates :body, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :category
  has_many :questions, dependent: :destroy
  belongs_to :author, class_name: 'User', optional: true
  has_many :test_passages, dependent: :destroy
  has_many :users, through: :test_passages, dependent: :destroy

  validates :title, presence: true
  validates_numericality_of :level, only_integer: true, grater_than_or_equal_to: 0
  validates :title, uniqueness: { scope: :level }

  scope :easy, -> { where(level: 0..1) }
  scope :medium, -> { where(level: 2..4) }
  scope :hard, -> { where(level: 5..Float::INFINITY) }
  scope :tests_by_category, -> (category) { joins(:category).where(categories: { title: category }) }


  def self.title_by_category(category)
    tests_by_category(category).order(title: :desc).pluck(:title)
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  SUCCESS = 85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_first_question, on: :create
  before_validation :before_validation_set_next_question, on: :update

  def accept!(answer_ids)
    if correct_answer?(answer_ids)
      self.correct_questions += 1
    end

    save!
  end

  def completed?
    current_question.nil?
  end

  def success?
    calculation >= SUCCESS
  end

  def test_questions_count
    test.questions.count
  end

  def calculation
    self.correct_questions * 100 / test_questions_count
  end

  def question_index
    test.questions.index(current_question) + 1
  end

  def total_questions
    test.questions.size
  end

  def time_out?
    (Time.now - self.created_at) > test.time_period if test.time_period
  end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.first if test.present?
  end

  def before_validation_set_next_question
    self.current_question = next_question
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.map(&:to_i).sort if answer_ids != nil
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    test.questions.order(:id).where('id > ?', current_question.nil? ? 0 : current_question.id).first
  end
end

app/models/tests_user.rb
class TestsUser < ApplicationRecord
  belongs_to :user
  belongs_to :test
end

app/models/user.rb
class User < ApplicationRecord
  EMAIL_FORMAT = /\A[a-zA-Z0-9._+]+@[a-zA-Zа-яА-Я._+]+\.[a-zа-я]+\z/

  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable,
         :trackable,
         :confirmable

  has_many :test_passages, dependent: :destroy
  has_many :tests, through: :test_passages
  has_many :author_tests, class_name: 'Test', foreign_key: 'author_id', dependent: :destroy
  has_many :gists, dependent: :destroy
  has_many :feedbacks, dependent: :destroy
  has_many :user_badges, dependent: :destroy
  has_many :badges, through: :user_badges

  validates :email, presence: true, uniqueness: true, format: { with: EMAIL_FORMAT }
  #validates :login, presence: true

  def tests_by_level(level)
    tests.where(level: level)
  end

  def completed_tests
    tests.where('test_passages.passed = ?', true)
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test_id: test.id)
  end

  def admin?
   is_a?(Admin)
  end
end

app/models/user_badge.rb
class UserBadge < ApplicationRecord
  belongs_to :user
  belongs_to :badge
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/badges_helper.rb
module BadgesHelper
  def badge_image(badge)
    if badge.image_url.present?
      badge_image.url
    else
      asset_path 'award.png'
    end
  end
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper

  def question_header(question)
    if question.new_record?
      "Create New Question: #{@test.title} "
    else
      "Edit Question #{question.test.title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tests_helper.rb
module TestsHelper

TEST_LEVELS = { 0 => :easy, 1 => :elementary, 2 => :advanced, 3 => :hard }.freeze

  def test_level(test)
    TEST_LEVELS[test.level] || :hero
  end
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Admin Panel | TestGuru</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav' %>
    <div class="container">
      <%= render 'shared/flash' %>
      <%= yield %><br>
    </div>

    <div class="container">
      <%= render 'shared/footer' %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>TestGuru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav' %><br>
    <div class="container">
      <%= render 'shared/flash' %>
      <%= yield %><br>
    </div>

    <div class="container">
    <%= render 'shared/footer' %>
  </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.present? %>
	<%= content_tag :div, class: 'alert alert-danger', role: 'alert', data: { resource_id: resource.id } do %>
	<h2><%= t('.header', count: resource.errors.count) %> </h2>

	<ul>
		<% resource.errors.full_messages.each do |message| %>
			<li><%= message %></li>
		<% end %>
	</ul>
	<% end %>
<% end %>

app/views/shared/_flash.html.erb
<% if flash.present? %>
	<% flash.each do |key, message| %>
		<div class="alert alert-<%= key %>" role="alert">
			<%= content_tag :p, message, class: "flash#{key}" %>
		</div>
	<% end %>
<% end %>

app/views/shared/_footer.html.erb
<div class="card-text"><small class="text-muted">
  	<h6 class="card-title"> Автор: Шамьянов Руслан</h6>
		Github: <%= github_link('xhpshamyrus', 'Test-Guru') %><br>
		<%= link_to 'Учебный проект в онлайн-школе Thinknetica', 'https://thinknetica.com', target: :_blank %></p>
		<%= current_year %><br>
	</small>
</div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-light bg-light">
	<%= link_to 'TestGuru', root_path, class: 'navbar-brand' %>

	<span class="navbar-text">
		<% if user_signed_in? %>
			 <% if current_user.admin? %>
				<%= link_to t('.admin'), admin_tests_path %> |
				<%= link_to t('.gists_table'), admin_gists_index_path, method: :get if current_user.admin? %> |
				<%= link_to t('.badges'), admin_badges_path %> |
			 	Welcome, <b> <%= current_user.first_name %><b> Guru! |
				<%= link_to t('.logout'), destroy_user_session_path, method: :delete %>
			 <% else %>
			 	<%= link_to t('.feedback'), new_feedback_path %> |
			 	<%= link_to t('.badges'), badges_path %> |
			 	<%= link_to t('.logout'), destroy_user_session_path, method: :delete %>
			 	<% end %>

		<% else %>
			<%= link_to t('.login'), new_user_session_path %> |
			<%= link_to t('.registration'), new_user_registration_path %>	
		<% end %>	
	</span>
</nav>

app/views/shared/_progress_bar.erb
<div class="progress-bar">
	<%= content_tag :div, " - #{@test_passage.question_index}/#{@test_passage.total_questions} - ",
									id: 'progress',
									data: { question_count: @test_passage.total_questions,
												  question_index: @test_passage.question_index - 1 } %>
</div>

app/views/shared/_timer.html.erb
<%= content_tag :div, '',
								id: 'timer', 
								data: { start_time: @test_passage.created_at.to_i, end_time: @test_passage.test.time_period } %> 